version: "3"

services:
  
  portainer:
    image: portainer/portainer:latest
    expose:
      - 9000
    restart: always
    environment:
      VIRTUAL_HOST: portainer.local
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    external:
      name: nginx-proxy
